name: Deploy
on:
  push:
    branches: [main]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: deploy to server
        uses: appleboy/ssh-action@master
        with:
          host: 146.190.226.222
          key: $(secrets.SSH_KEY)
          username: $(secrets.SSH_USERNAME)

          script: |
            cd /var/www/main/lumen-microservice
            git fetch origin main
            git reset --hard FETCH_HEAD
            git clean -d -f --exclude secrets
            chown $(whoami)
            echo 'Deployment successful'
