name: Laravel
on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  laravel-tests:

    runs-on: ubuntu:20.00

    steps:
    - uses: actions/checkout@v3
    - uses: actions/cache@v3.0.5
      with:
        key: jjbbgg
    - run: docker-compose up -d
    - run: ./vendor/bin/phpunit
