name: CI

on: [push]

jobs:
  tests:
    name: Run PHP tests
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v1

      - name: Setup Github token for private repos
        run: composer config -g github-oauth.github.com ${{ secrets.GITHUB_ACCESS_TOKEN }}

      - name: Cache composer dependencies
        uses: actions/cache@v1
        with:
          path: vendor
          key: composer-${{ hashFiles('composer.lock') }}

      - name: Install composer depedencies
        run: composer install -n --prefer-dist --no-scripts --no-progress

      - name: Setup locales
        run: sudo locale-gen sv_SE.UTF-8

      - name: Prepare Laravel
        run: |
          cp .env.example .env
      - name: Disable xdebug
        run: sudo phpdismod -s cli xdebug

      - name: Create database
        run: mysql -u root -proot -e 'CREATE DATABASE '"app"';'

      - name: Run tests
        run: composer test
        env:
          DB_DATABASE: app
          DB_USERNAME: root
          DB_PASSWORD: root
